import type { Project } from "@/types";

/**
 * Données STRUCTURELLES des projets (non traduisibles).
 * Les textes (descriptions, légendes, étude de cas…) vivent dans les
 * catalogues i18n sous "Portfolio" et "Projects".
 */
export const projects: Project[] = [
  {
    id: "megareco",
    title: "MegaReco",
    url: "https://www.megareco.com",
    status: "real-client",
    sector: null,
    posterImage: "/images/megareco-homepage.png",
    images: {
      homepage: "/images/megareco-homepage.png",
      logo: "/images/megareco-logo.png",
    },
    techStack: [
      { name: "Vue.js 3", color: "gold" },
      { name: "Node.js", color: "primary" },
      { name: "Express", color: "primary" },
      { name: "PostgreSQL", color: "gold" },
      { name: "JavaScript", color: "default" },
      { name: "Neon", color: "default" },
      { name: "Render", color: "default" },
      { name: "Vercel", color: "default" },
    ],
    gallerySrc: [
      "/images/megareco-homepage.png",
      "/images/megareco-detail.png",
      "/images/megareco-profile.png",
      "/images/megareco-admin.png",
      "/images/megareco-login.png",
    ],
    tags: [
      "Full-Stack",
      "Vue.js",
      "Auth",
      "OAuth",
      "Admin",
      "Profils",
      "Commentaires",
      "Notation",
      "Gamification",
      "Tracking",
      "Responsive",
      "UX/UI",
      "REST API",
    ],
    caseStudy: {
      mobileImage: "/images/megareco-mobile.png",
      featureIcons: ["Search", "User", "MessageSquare", "Trophy"],
      challengeIcons: ["Lock", "Trophy", "LayoutDashboard", "Smartphone"],
    },
    featured: true,
    descriptor: "Communauté · Application web",
  },
  {
    id: "megataste",
    title: "MegaTaste",
    url: "https://mega-taste.vercel.app/",
    status: "demo-live",
    sector: "restaurant",
    posterImage: "/images/megataste-homepage.png",
    images: {
      homepage: "/images/megataste-homepage.png",
    },
    techStack: [
      { name: "Next.js 15", color: "default" },
      { name: "TailwindCSS v4", color: "gold" },
      { name: "Framer Motion", color: "primary" },
      { name: "TypeScript", color: "primary" },
      { name: "Vercel", color: "default" },
    ],
    tags: ["Site vitrine", "Next.js", "Responsive", "Animations", "Restaurant", "UX/UI"],
    featured: true,
    descriptor: "Restaurant · Site vitrine",
  },
  {
    id: "atelier-cendre-chene",
    title: "Atelier Cendre & Chêne",
    url: "https://demo-atelier-cendre-chene.vercel.app/",
    status: "demo-live",
    sector: "artisans",
    pairSlug: "artisans",
    posterImage: "/images/demos/atelier-cendre-chene.jpg",
    images: { homepage: "/images/demos/atelier-cendre-chene.jpg" },
    descriptor: "Artisans · Site vitrine",
    teaser: "Une matière brute mise en valeur, du grain du bois à la présentation du geste.",
  },
  {
    id: "maison-trait-juste",
    title: "Maison Trait Juste",
    url: "https://demo-maison-trait-juste.vercel.app/",
    status: "demo-live",
    sector: "artisans",
    pairSlug: "artisans",
    posterImage: "/images/demos/maison-trait-juste.jpg",
    images: { homepage: "/images/demos/maison-trait-juste.jpg" },
    descriptor: "Artisans · Site vitrine",
    teaser: "Un trait sobre et précis, pensé pour donner confiance au premier regard.",
  },
  {
    id: "liora-venn-studio",
    title: "Liora Venn Studio",
    url: "https://demo-liora-venn-studio.vercel.app/",
    status: "demo-live",
    sector: "artistes",
    pairSlug: "artistes",
    posterImage: "/images/demos/liora-venn-studio.jpg",
    images: { homepage: "/images/demos/liora-venn-studio.jpg" },
    descriptor: "Artistes · Site vitrine",
    teaser: "Une scénographie épurée qui laisse toute la place à l'œuvre.",
  },
  {
    id: "atelier-noemie-aster",
    title: "Atelier Noémie Aster",
    url: "https://demo-atelier-noemie-aster.vercel.app/",
    status: "demo-live",
    sector: "artistes",
    pairSlug: "artistes",
    posterImage: "/images/demos/atelier-noemie-aster.jpg",
    images: { homepage: "/images/demos/atelier-noemie-aster.jpg" },
    descriptor: "Artistes · Site vitrine",
    teaser: "Un espace clair, pensé comme un accrochage numérique.",
  },
  {
    id: "velune",
    title: "Velune",
    url: "https://demo-velune.vercel.app/",
    status: "demo-live",
    sector: "startup",
    pairSlug: "startup",
    posterImage: "/images/demos/velune.jpg",
    images: { homepage: "/images/demos/velune.jpg" },
    descriptor: "Startup · Site vitrine",
    teaser: "Un message clair et direct pour porter un projet naissant.",
  },
  {
    id: "kerno-systems",
    title: "Kerno Systems",
    url: "https://demo-kerno-systems.vercel.app/",
    status: "demo-live",
    sector: "startup",
    pairSlug: "startup",
    posterImage: "/images/demos/kerno-systems.jpg",
    images: { homepage: "/images/demos/kerno-systems.jpg" },
    descriptor: "Startup · Site vitrine",
    teaser: "Une image technique et rassurante, pensée pour convaincre vite.",
  },
  {
    id: "maison-sepia",
    title: "Maison Sépia",
    url: "https://demo-maison-sepia.vercel.app/",
    status: "demo-live",
    sector: "restaurant",
    pairSlug: "restaurant",
    posterImage: "/images/demos/maison-sepia.jpg",
    images: { homepage: "/images/demos/maison-sepia.jpg" },
    descriptor: "Restaurant · Site vitrine",
    teaser: "Une ambiance feutrée, pensée pour donner envie de réserver.",
  },
  {
    id: "les-trois-aulnes",
    title: "Les Trois Aulnes",
    url: "https://demo-les-trois-aulnes.vercel.app/",
    status: "demo-live",
    sector: "restaurant",
    pairSlug: "restaurant",
    posterImage: "/images/demos/les-trois-aulnes.jpg",
    images: { homepage: "/images/demos/les-trois-aulnes.jpg" },
    descriptor: "Restaurant · Site vitrine",
    teaser: "Une salle et une carte racontées avec la même attention.",
  },
  {
    id: "atelier-monolithe",
    title: "Atelier Monolithe",
    url: "https://atelier-monolithe-vercel.vercel.app/",
    status: "demo-live",
    sector: "architecte",
    pairSlug: "architecte",
    posterImage: "/images/demos/atelier-monolithe.jpg",
    images: { homepage: "/images/demos/atelier-monolithe.jpg" },
    descriptor: "Architecte · Site vitrine",
    teaser: "Une mise en espace sobre, au service du travail présenté.",
  },
  {
    id: "studio-trame-27",
    title: "Studio Trame 27",
    url: "https://studio-trame-27-vercel.vercel.app/",
    status: "demo-live",
    sector: "architecte",
    pairSlug: "architecte",
    posterImage: "/images/demos/studio-trame-27.jpg",
    images: { homepage: "/images/demos/studio-trame-27.jpg" },
    descriptor: "Architecte · Site vitrine",
    teaser: "Une grille précise, fidèle à la rigueur du dessin d'exécution.",
  },
  {
    id: "kairo-nocturne",
    title: "Kairo Nocturne",
    url: "https://kairo-nocturne-vercel.vercel.app/",
    status: "demo-live",
    sector: "musicien",
    pairSlug: "musicien",
    posterImage: "/images/demos/kairo-nocturne.jpg",
    images: { homepage: "/images/demos/kairo-nocturne.jpg" },
    descriptor: "Musicien · Site vitrine",
    teaser: "Une scène numérique pensée pour l'écoute autant que pour l'image.",
  },
  {
    id: "sillon-88",
    title: "Sillon 88 Records",
    url: "https://sillon-88-vercel.vercel.app/",
    status: "demo-live",
    sector: "musicien",
    pairSlug: "musicien",
    posterImage: "/images/demos/sillon-88.jpg",
    images: { homepage: "/images/demos/sillon-88.jpg" },
    descriptor: "Musicien · Site vitrine",
    teaser: "Un catalogue mis en scène comme une collection à part entière.",
  },
  {
    id: "maison-elyra",
    title: "Maison Elyra",
    url: "https://maison-elyra-vercel.vercel.app/",
    status: "demo-live",
    sector: "mode",
    pairSlug: "mode",
    posterImage: "/images/demos/maison-elyra.jpg",
    images: { homepage: "/images/demos/maison-elyra.jpg" },
    descriptor: "Mode · Site vitrine",
    teaser: "Une allure épurée, fidèle à l'exigence du geste couture.",
  },
  {
    id: "nomae-studio",
    title: "Nomae Studio",
    url: "https://nomae-studio-vercel.vercel.app/",
    status: "demo-live",
    sector: "mode",
    pairSlug: "mode",
    posterImage: "/images/demos/nomae-studio.jpg",
    images: { homepage: "/images/demos/nomae-studio.jpg" },
    descriptor: "Mode · Site vitrine",
    teaser: "Une silhouette affirmée, portée par une mise en page graphique.",
  },
  {
    id: "studio-souffle",
    title: "Studio Souffle",
    url: "https://studio-souffle-vercel.vercel.app/",
    status: "demo-live",
    sector: "bien-etre",
    pairSlug: "bien-etre",
    posterImage: "/images/demos/studio-souffle.jpg",
    images: { homepage: "/images/demos/studio-souffle.jpg" },
    descriptor: "Bien-être · Site vitrine",
    teaser: "Un espace apaisé, à l'image d'une pratique du soin.",
  },
  {
    id: "source-canopee",
    title: "Source & Canopée",
    url: "https://source-canopee-vercel.vercel.app/",
    status: "demo-live",
    sector: "bien-etre",
    pairSlug: "bien-etre",
    posterImage: "/images/demos/source-canopee.jpg",
    images: { homepage: "/images/demos/source-canopee.jpg" },
    descriptor: "Bien-être · Site vitrine",
    teaser: "Une respiration végétale, pensée comme un espace de ressourcement.",
  },
];
